server:
  port: 1011

spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://localhost:5438/bank?currentSchema=account
    username: yandex
    password: yandex
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/