server:
  port: ${SERVER_PORT:1011}
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5438/bank?currentSchema=account}
    username: ${DB_USERNAME:yandex}
    password: ${DB_PASSWORD:yandex}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: account
  thymeleaf:
    encoding: UTF-8
  liquibase:
    change-log: classpath:/db/changelog/rootChangeLog.xml
    liquibase-schema: public
    default-schema: account
    parameters:
      schemaName: account
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5438/bank?currentSchema=account}
    user: ${DB_USERNAME:yandex}
    password: ${DB_PASSWORD:yandex}
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI:http://localhost:8888/realms/bankapp}
        registration:
          bankapp:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: bankapp
            client-secret: Xih8xBTW8WuoJvBRFzuhQ8DXbxdONfec
            scope:
              - profile
            client-authentication-method: client_secret_post
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

app:
  feign:
    exchange-service:
      url: ${APP_FEIGN_EXCHANGE_SERVICE_URL:http://localhost:1016/exchange}
    notification-service:
      url: ${APP_FEIGN_NOTIFICATION_SERVICE_URL:http://localhost:1018/notification}
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    liquibase:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.boot.actuate: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.web: DEBUG
    org.company.account: DEBUG
    liquibase: INFO

eureka:
  client:
    enabled: false