server:
  port: 0

spring:
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/realms/bankapp
        registration:
          bankapp:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: bankapp
            client-secret: Xih8xBTW8WuoJvBRFzuhQ8DXbxdONfec
            scope:
              - profile
            client-authentication-method: client_secret_post
eureka:
  client:
    register-with-eureka: false