spring:
  config:
    import: optional:configserver:http://localhost:1012
  profiles:
    active: default
  cloud:
    config:
      label: main
app:
  feign:
    exchange-service:
      url: ${APP_FEIGN_EXCHANGE_SERVICE_URL:http://localhost:1016/exchange}