spring:
  config:
    import: optional:configserver:http://localhost:1012
  cloud:
    config:
      label: main
app:
  feign:
    account-service:
      url: ${APP_FEIGN_ACCOUNT_SERVICE_URL:http://localhost:1011/}
    cash-service:
      url: ${APP_FEIGN_CASH_SERVICE_URL:http://localhost:1017/}
    exchange-service:
      url: ${APP_FEIGN_EXCHANGE_SERVICE_URL:http://localhost:1016/}
    transfer-service:
      url: ${APP_FEIGN_TRANSFER_SERVICE_URL:http://localhost:1013/}