server:
  port: 0

spring:
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/realms/bankapp
        registration:
          bankapp:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: bankapp
            client-secret: Xih8xBTW8WuoJvBRFzuhQ8DXbxdONfec
            scope:
              - profile
            client-authentication-method: client_secret_post
app:
  feign:
    account-service:
      url: ${APP_FEIGN_ACCOUNT_SERVICE_URL:http://localhost:1011/account}
    cash-service:
      url: ${APP_FEIGN_CASH_SERVICE_URL:http://localhost:1017/cash}
    exchange-service:
      url: ${APP_FEIGN_EXCHANGE_SERVICE_URL:http://localhost:1016/exchange}
    transfer-service:
      url: ${APP_FEIGN_TRANSFER_SERVICE_URL:http://localhost:1013/transfer}
eureka:
  client:
    register-with-eureka: false