server:
  port: 0

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/realms/master
eureka:
  client:
    register-with-eureka: false