global:
  domain: bank.local
  database:
    host: "bank-app-shared-db"
    port: 5432
    name: "bankapp"
    username: "bankapp"

transfer-service:
  config:
    database_url: "jdbc:postgresql://bank-app-shared-db:5432/bankapp?currentSchema=transfer"
    database_username: "bankapp"

notification-service:
  config:
    database_url: "jdbc:postgresql://bank-app-shared-db:5432/bankapp?currentSchema=notification"
    database_username: "bankapp"

exchange-service:
  config:
    database_url: "jdbc:postgresql://bank-app-shared-db:5432/bankapp?currentSchema=exchange"
    database_username: "bankapp"

cash-service:
  config:
    database_url: "jdbc:postgresql://bank-app-shared-db:5432/bankapp?currentSchema=cash"
    database_username: "bankapp"

account-service:
  config:
    database_url: "jdbc:postgresql://bank-app-shared-db:5432/bankapp?currentSchema=account"
    database_username: "bankapp"

shared-db:
  enabled: true
  image:
    repository: bitnamilegacy/postgresql
    tag: 16.2.0-debian-12-r5
    pullPolicy: IfNotPresent
  auth:
    database: bankapp
    username: bankapp
    password: "changeM3Customer!" # Example: Not recommended for production
  primary:
    persistence:
      enabled: true
      size: 1Gi

app-kafka:
  enabled: true

  image:
    repository: bitnamilegacy/kafka
    tag: 3.3.2
    pullPolicy: IfNotPresent

  # Явно отключаем KRaft и используем только Zookeeper
  kraft:
    enabled: false

  zookeeper:
    enabled: true

  # Конфигурация для работы с Zookeeper
  config:
    "zookeeper.connect": "bank-app-app-zookeeper:2181"
    "log.flush.interval.messages": "500000"
    # Исправляем настройки репликации для development с 1 брокером
    "offsets.topic.replication.factor": 1
    "transaction.state.log.replication.factor": 1
    "transaction.state.log.min.isr": 1
    "default.replication.factor": 1
    "min.insync.replicas": 1
    # Дополнительные настройки
    "num.partitions": 1

  # Отключаем все KRaft-related настройки
  processRoles: ""  # Пустая строка для отключения KRaft
  clusterId: ""     # Пустая строка

  controller:
    replicaCount: 3
    persistence:
      enabled: false
    readinessProbe:
      enabled: false

  broker:
    replicaCount: 3
    persistence:
      enabled: false


app-zookeeper:
  image:
    repository: bitnamilegacy/zookeeper
    tag: 3.9.3-debian-12-r22
    pullPolicy: IfNotPresent