spring:
  config:
    import: optional:configserver:http://localhost:1012
  cloud:
    config:
      label: main
app:
  feign:
    account-service:
      url: ${APP_FEIGN_ACCOUNT_SERVICE_URL:http://localhost:1011/}
    blocker-service:
      url: ${APP_FEIGN_BLOCKER_SERVICE_URL:http://localhost:1020/}
    notification-service:
      url: ${APP_FEIGN_NOTIFICATION_SERVICE_URL:http://localhost:1018/}