apiVersion: v1
kind: ConfigMap
metadata:
  name: blocker-service-cm
data:
  SERVER_PORT: "8080"
  SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: "http://bank-app-keycloak-service:8888/realms/bankapp"
