apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-service
  template:
    metadata:
      labels:
        app: front-service
    spec:
      containers:
        - name: front-service
          image: front-service:1.0
          ports:
            - containerPort: 1010
          envFrom:
            - configMapRef:
                name: front-service-cm

---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort
  selector:
    app: front-service
  ports:
    - port: 1010        # Порт внутри кластера
      targetPort: 1010  # Порт внутри контейнера

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-service-cm
data:
  SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: "http://keycloak.default.svc.cluster.local:8888/realms/bankapp"
  SPRING_PROFILES_ACTIVE: "kuber"